### ISSUE TITLE
Adding objects to AnnData from R with reticulate

### ISSUE THREAD

**Issue by ndrubins** [theislab/scanpy#1331]
Hi,

I'm using `scanpy` from `R` with `reticulate` and I'm creating several `R` `data.frame`s  (e.g. `my_df` below) that I would like to add to the `AnnData` object (e.g., under `obsm`) and save that modified `AnnData` as an `h5ad` file.

If for example, I read an existing `AnnData` h5ad file (`in.h5ad.fn` below) in `R` with `reticulate` using:
```
library(reticulate)
sc <- import("scanpy")
adata <- sc$read(in.h5ad.fn)

```

Then created:
`my_df <- data.frame(cell = rownames(adata$obs), value = rnorm(nrow(adata$obs))
`

I thought that:
`adata$obsm['my_df'] <- my_df
`

would work but I get this error:
```
Error in adata$obsm["my_df"] = my_df :
  object of type 'environment' is not subsettable
 
```

What's the proper way to add `my_df` to `adata`?
And what would be the command to save that modified `adata` object to an `h5ad` file?

**Comment by flying-sheep** [comment]
Reticulate doesn’t wrap `__getitem__`/`__setitem__` with R’s `[` and `[<-` methods directly. For the getitem case, it instead uses some complex code that tries to do something smart (mostly a bad idea):

https://github.com/rstudio/reticulate/blob/6e44eff5fe8f7f1cad9d9c96f23fe9d79e9f8189/R/python.R#L277-L355

What’s missing is the setitem case for `[]`, as only the `$<-.python.builtin.object` and `[[<-.python.builtin.object` are defined. You can just use (`py_get_item`)[https://rstudio.github.io/reticulate/reference/py_get_item.html]/[`py_set_item`](https://rstudio.github.io/reticulate/reference/py_set_item.html) directly, or define the missing method:

```r
`[<-.python.builtin.object` <- py_set_item
```

I filed this bug in the correct repo accordingly: rstudio/reticulate#803

**Comment by ndrubins** [comment]
Thank you very much for the quick response.

I need to make a small correction to my post above. The proper slot for `my_df` in `adata` should `adata.uns` rather than `adata.obsm`.

Following your answer, in `R` I did: 

`adata$uns <- reticulate::py_set_item(adata$uns, 'my_df' ,my_df)
`
But I get this error:
```
Error in py_set_item_impl(x, name, value) :
  Unable to access object (object is from previous session and is now invalid)

```

When I try to do the same in `python` (first reading in the `my_df` `data.frame` from an `RDS` file I saved it to in `R`):
```
import pandas as pd
import scanpy as sc
import pyreadr
my_df = pyreadr.read_r(my_df_fn)
adata.uns['my_df'] = my_df

```

It works fine - `adata` already had `neighbors` and `pca` under `uns` and `my_df` gets added.

Any idea what am I doing wrong?

Thanks

**Comment by flying-sheep** [comment]
You don’t need to do an assignment. Python objects are by-reference, so you just do `py_set_item(adata$uns, ...)` and `adata$uns` will be updated

**Comment by ndrubins** [comment]
Sorry for being persistent but I'm still getting the same error.

The `adata` object I'm working with is the one from [`scanpy`'s pbmc3k tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html).
Either saving the `adata` object as an `h5ad` (`adata.h5ad`) before running `PCA` (hence when `adata` only has the `var` and `obs` slots) or after (when it has the `uns` slot), then reading it in `R` and trying to add `my_df`:
```
library(reticulate)
import pandas as pd
import scanpy as sc
adata <- sc$read('adata.h5ad')
set.seed(1)
my_df <- data.frame(x = rnorm(100), y = rnorm(100))
reticulate::py_set_item(adata$uns, 'my_df', my_df)

```

I get:
```
Error in py_set_item_impl(x, name, value) :
  Unable to access object (object is from previous session and is now invalid)

```

**Comment by flying-sheep** [comment]
Hmm, I think the reticulate people can help you better with that than I can.

**Comment by ndrubins** [comment]
Thanks.
One last small question. which you may also find to be relevant to `reticulate`:
If I add `my_df` to `adata$uns` in `python`:
`adata.uns['my_df'] = my_df
`

I see it properly added as a `data.frame` along with the column names:
```
>>> type(adata.uns['my_df'])
<class 'pandas.core.frame.DataFrame'>

```

and:
```
>>> adata.uns['my_df']
           x         y
0   0.299158 -0.514339
1  -1.994057 -0.905130
2   1.536284 -1.090005

```


Then, if I save it as an `h5ad` using `adata.write('adata_my_df.h5ad')`, and then read it in `R` using `reticulate`, I see that `adata$uns$my_df` is now a `matrix` and the column names are not there:
```
pd <- import("pandas")
sc <- import("scanpy")
adata <- sc$read("adata_my_df.h5ad")
> class(adata$uns$my_df)
[1] "matrix"
> head(adata$uns$my_df)
           [,1]       [,2]
[1,]  0.2991581 -0.5143395
[2,] -1.9940568 -0.9051297
[3,]  1.5362842 -1.0900054

```

Any idea?

**Comment by flying-sheep** [comment]
There’s a few parts here:

1. adding the data frame to `uns` (it doesn’t get converted here)
2. writing the AnnData object to disk
3. reading it from disk
4. converting the Python data structure to R by reticulate

You can try reading the file from Python. If it’s already been converted then, the conversion happens during reading or writing, but not in reticulate. If it happens during reading or writing, you can use [HDF5 tools](https://support.hdfgroup.org/products/hdf5_tools/) to [inspect the file](https://anndata.readthedocs.io/en/stable/fileformat-prose.html) and check if the thing is stored as a data frame or a matrix.

**Comment by ndrubins** [comment]
Sorry for not being specific.

This is happening independently of `reticulate`, completely in `python`. 

For the sake of clarity here's the complete process.

1. Read `adata` that does not include `my_df`:
```
>>> import pandas as pd
>>> import scanpy as sc
>>> import pyreadr
>>> adata = sc.read('adata.h5ad')
>>> adata
AnnData object with n_obs × n_vars = 2638 × 13714
    obs: 'n_genes', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt'
    var: 'gene_ids', 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'pca'
    obsm: 'X_pca'
    varm: 'PCs'

```

2. Read `my_df` from the `RDS` file I saved it to in `R`:
```
>>> my_df = pyreadr.read_r('my_df.RDS')
>>> my_df = my_df[None]
>>> type(my_df)
<class 'pandas.core.frame.DataFrame'>
>>> my_df
           x         y
0   0.299158 -0.514339
1  -1.994057 -0.905130
2   1.536284 -1.090005
3  -0.825919 -0.165101

```

3. Add `my_df` to `adata.uns` and make sure it's added as a `pandas` `dataframe` with the column names:
```
>>> adata.uns['my_df'] = my_df
>>> adata
AnnData object with n_obs × n_vars = 2638 × 13714
    obs: 'n_genes', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt'
    var: 'gene_ids', 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'pca', 'my_df'
    obsm: 'X_pca'
    varm: 'PCs'
>>> type(adata.uns['my_df'])
<class 'pandas.core.frame.DataFrame'>
>>> adata.uns['my_df']
           x         y
0   0.299158 -0.514339
1  -1.994057 -0.905130
2   1.536284 -1.090005

```

4. Save this modified `adata` to an `h5ad` file:
`adata.write('adata_my_df.h5ad')
`

5. Quit this `python` session, start a new one, and read `adata_my_df.h5ad`:
```
>>> import pandas as pd
>>> import scanpy as sc
>>> adata = sc.read('adata_my_df.h5ad')

```

6. First make sure that my_df is indeed in in `adata`'s `uns` slot:
```
>>> adata
AnnData object with n_obs × n_vars = 2638 × 13714
    obs: 'n_genes', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt'
    var: 'gene_ids', 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'my_df', 'pca'
    obsm: 'X_pca'
    varm: 'PCs'


```

7. Show that `my_df` is actually `numpy.ndarray` (which I guess is why reticulate reads reads it as a `matrix` in `R`) and the column names are gone:
```
>>> adata.uns['my_df']
array([[ 2.99158071e-01, -5.14339494e-01],
       [-1.99405676e+00, -9.05129703e-01],
       [ 1.53628424e+00, -1.09000536e+00],
       [-8.25918690e-01, -1.65100861e-01],
       [-4.19977424e-01,  1.22236926e+00],

```

**Comment by flying-sheep** [comment]
as said: it’s unclear if the file is stored on disk as data frame or as array. between 4 and 5 you should figure out what’s the case here, then we can see if the problem is in the write function or the read function

**Comment by ndrubins** [comment]
This is what I see when inspecting the `adata_my_df.h5ad` file:

```
>>> import h5py
>>> import scipy
>>> import scanpy
>>> import pandas
>>> f = h5py.File("/home/nrubinstein/Downloads/adata_my_df.h5ad", "r")
>>> list(f.keys())
['X', 'obs', 'obsm', 'uns', 'var', 'varm']
>>> f["uns"].visititems(print)
my_df <HDF5 dataset "my_df": shape (100, 2), type "<f8">
pca <HDF5 group "/uns/pca" (2 members)>
pca/variance <HDF5 dataset "variance": shape (50,), type "<f4">
pca/variance_ratio <HDF5 dataset "variance_ratio": shape (50,), type "<f4">

```

I couldn't really tell from the [`HDF5` inspection documentation](https://anndata.readthedocs.io/en/stable/fileformat-prose.html) you referred me to whether this output means that `my_df` is a `dataframe` or a `dense array`.

This probably doesn't matter, but indexing `my_df` before adding it to the `uns` slot in `adata` doesn't change much other than the dimensions and type of `my_df` that `f["uns"].visititems(print)` reports.

**Comment by flying-sheep** [comment]
it’s stored as a `dataset`, so it’s a dense array. data frames are stored as `group`s (think folders)

therefore the problem is in the write function.
